server:
  port: 8762

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
    enable-self-preservation: false # 设为false，关闭自我保护
    eviction-interval-timer-in-ms: 60000 # 清理间隔（单位毫秒，默认是60*1000）
