server:
  port: 8070
spring:
  application:
    name: springconfigserver
  cloud:
    config:
      server:
        git: 
          uri: https://github.com/chenpeihai1026/springcloudconfigserver.git
          search-paths: config-repo
          username: chenpeihai1026
          password: Peihai!!2005
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/       